[preview]
command = "nvim"
args = ["--headless", "-c", "set runtimepath+=~/.vim", "-c", "source ~/.vimrc", "-c", "edit %"]

[open]
use = [
    "rules",
]

[[rules]]
name = "*.cpp"
exec = "nvim \"$1\""

[[rules]]
name = "*.py"
exec = "nvim \"$1\""

[[rules]]
mime = "text/*"
exec = "nvim \"$1\""
